### ISSUE TITLE
Password Reset not working

### ISSUE THREAD

**Issue by dimitrist19** [dimitrist19/tutorials-site-cms#3]
Due to some small changes from v1 to v1.1 the password reset is not working anymore. A fix will be pushed soon.

**Comment by FatGrizzly** [comment]
@dimitrist19 
I have the same bug on Beta version
p.s I left discord, so couldn't contact you there

**Comment by FatGrizzly** [comment]
and the notifications messages go out(kinda)
![image](https://user-images.githubusercontent.com/66728880/122330000-ff729f00-cf4f-11eb-8c3c-847d9f104bc4.png)

**Comment by dimitrist19** [comment]
I've fixed both. Thanks for making me aware of the issues :)
